name: Static analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Tarantool
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: "2.10"

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/3/installer.sh | bash
          sudo apt-get -y install tt

      - name: Setup dependencies
        run: make deps

      - name: Run static analysis
        run: make check
